### ISSUE TITLE
Usage of scapy exception instead of custom error message

### ISSUE THREAD

**Issue by paulogonc** [solsticedhiver/probemon#2]
Hi, thanks for sharing your project. I've installed it (version 0.7) on my Raspi using a mini conda environment. At the beginning I was a little bit confused with the error message which where thrown from the following try except block `print(f"Error: {args.interface} interface not found", file=sys.stderr)`. In my case it was not related to a wrong interface. The tcpdum package wasn't installed on the raspi. So I could figure it out, after deleting the try except block an let scapy throw the error message, which was: 

`raise Scapy_Exception("tcpdump is not available. Cannot use filter !")
scapy.error.Scapy_Exception: tcpdump is not available. Cannot use filter !`  

So, afterwards  the root cause analysis was for me much more easier. Maybe you would like to add the possibility into your code to report the error message directly from scapy. 

Thanks and best regards

**Comment by solsticedhiver** [comment]
Yes. Of course. fixed with cad010e9
